# Generated by Django 4.0.5 on 2023-05-10 13:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('expenses', models.IntegerField()),
                ('income', models.IntegerField()),
            ],
        ),
    ]
