# Generated by Django 4.0.5 on 2023-03-21 20:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenses', models.CharField(blank=True, choices=[('a', 'Advertising'), ('f', 'Fees'), ('m', 'Misc'), ('w', 'Wages'), ('u', 'Utilities')], help_text='Choose business expense type', max_length=1)),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mileage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('personal', models.IntegerField(help_text='Enter personal use miles')),
                ('business', models.IntegerField(help_text='Enter business use miles')),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('job_name', models.CharField(blank=True, help_text='Enter name for job you are tracking', max_length=200)),
                ('client', models.CharField(blank=True, help_text='Enter clients name', max_length=100)),
                ('date', models.DateTimeField()),
                ('expenses', models.ManyToManyField(to='jobs.expenses')),
                ('mileage', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='jobs.mileage')),
            ],
            options={
                'ordering': ['client'],
            },
        ),
    ]
