# Generated by Django 4.0.5 on 2023-03-28 14:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField(blank=True, default=0, help_text='Enter amount earned')),
            ],
            options={
                'ordering': ['amount'],
            },
        ),
        migrations.AddField(
            model_name='jobs',
            name='income',
            field=models.ManyToManyField(to='jobs.income'),
        ),
    ]
