# Generated by Django 4.0.5 on 2023-03-21 20:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(help_text='Enter product name', max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('inv', models.IntegerField(blank=True, help_text='Enter current inventory', null=True)),
                ('description', models.TextField(blank=True, help_text='Enter a description of your products', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=100, null=True)),
                ('Items', models.ManyToManyField(to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('email', models.EmailField(help_text='Enter business email', max_length=254, primary_key=True, serialize=False)),
                ('phone', models.IntegerField(help_text='Enter business phone number', max_length=12)),
                ('message', models.TextField(blank=True, help_text='leave a brief message for clients', null=True)),
                ('storefront', models.ForeignKey(blank=True, help_text='Storefront for business', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.store')),
            ],
            options={
                'ordering': ['email'],
            },
        ),
    ]
