# Generated by Django 4.0.5 on 2023-03-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='storefront',
        ),
        migrations.AddField(
            model_name='business',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='business',
            name='email',
            field=models.EmailField(help_text='Enter business email', max_length=254),
        ),
    ]
