# Generated by Django 4.0.5 on 2023-03-28 02:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_business_id_alter_business_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='business',
            name='email',
            field=models.EmailField(help_text='Enter business email', max_length=254),
        ),
    ]
