# Generated by Django 4.0.5 on 2023-05-22 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_business_id_alter_business_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='Items',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
