# Generated by Django 4.0.5 on 2023-05-10 23:48

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('due_date', models.DateTimeField(default=datetime.datetime(2023, 5, 10, 23, 48, 43, 662844))),
                ('description', models.TextField()),
            ],
        ),
    ]
