# Generated by Django 4.0.5 on 2023-05-11 00:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_alter_bills_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 11, 0, 11, 18, 393002)),
        ),
    ]
