name: ci

on:
  push:
    branches:
      - "Portfolio"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: portfolio/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/9fc8000db61996de87f77ae275322265d16cd4a2f6a5b8430cdf69c9e4f0f6ec
